spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: consumer
  cloud:
    nacos:
      discovery:
        server-addr: 42.56.89.59:8848

server:
  port: 10201

dubbo:
  application:
    name: consumer
    qos-enable: false
  registry:
    address: nacos://42.56.89.59:8848
  scan:
    basePackages: com.htd.alibaba.dubbo.consumer.service

management:
  endpoints:
    web:
      exposure:
        include: "*"